name: bts_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Supports Dart 3.x and Flutter 3.x

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # Compatible with Dart 3
  sqflite: ^2.2.0 # Supports null safety
  path_provider: ^2.0.13 # Null safety supported
  http: ^1.2.2
  dio: ^5.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg.jpg
    - assets/icons/
